version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    
    working_directory: ~/project
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm i 

      - run: 
          name: Deploying on master branch
          command: |
            # Only push docker image when on master branch on the Accedian project
            if [[ "${CIRCLE_BRANCH}" == "master" || "${CIRCLE_BRANCH}" == "release/"* ]] && [ "${CIRCLE_PROJECT_USERNAME}" == "Accedian" ]; then
              npm run deploy
            fi

            #      - run: 
            #          name: Deploying on other branch
            #          command: |
            #            # Only push docker image when on master branch on the Accedian project
            #            if [[ "${CIRCLE_BRANCH}" != "master" && "${CIRCLE_BRANCH}" != "release/"* && "${CIRCLE_BRANCH}" != "gh-pages" ]] && [ "${CIRCLE_PROJECT_USERNAME}" == "Accedian" ]; then
            #              npm run deploy-branch
            #            fi




      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        

workflows:
  version: 2
  build_and_release: 
    jobs:
      - build:
          context: org-global
          filters:
            branches:
              only: 
                - master
                - /release\/.*/

